### ISSUE TITLE
FEEDBACK:

### ISSUE THREAD

**Issue by NatalyPorras** [Geraldine13/lim20181-Track-FE-markdown-list#1]
- Archivos js: Muy buena organización de tu código diviendolo en archivos. Respecto a los espacios entre funciones, toma referencia de la guía de estilos, asimismo evita los comentarios de código que ya no utilizaras.
- Readme: Ten encuenta que el archivo readme es la presentación de tu paquete, por lo tanto detalla y especifica su instalación, uso y utiliza ejemplos.

**Comment by Geraldine13** [comment]
Estimada Nataly,

Gracias por tu feedback, se tomará en cuenta en el proyecto.

Saludos,
