### ISSUE TITLE
Feetback tech

### ISSUE THREAD

**Issue by GabyMarapi** [Geraldine13/lim20181-Track-FE-markdown-list#11]
Amiga Geral.

Solo a modo de recordar, no te olvides de los links únicos.  
 resultFinal.unique = [...new Set(objTotalLinks)].length;

te recomiendo utilizar el extname de node.js para validar que el archivo sea un md

https://nodejs.org/api/path.html#path_path_extname_path 

Me encanta tu trabajo Geral, sigue asiiiii :D

**Comment by Geraldine13** [comment]
Gracias Gaby.
