### ISSUE TITLE
Feedback Técnico

### ISSUE THREAD

**Issue by RuthSalvador** [Geraldine13/lim20181-Track-FE-markdown-list#12]
# Recomendaciones de mejora 

### Estructura de carpetas, documentación, package.json:
Está bien que hayas descrito tu librería y los pasos que se deben usar.

### Git y Github:
Bien, trata de investigar sobre [releases](https://help.github.com/articles/creating-releases/)

### Javascript:
- Bien que utilices variables descriptivas y en inglés.
- Bien, está factorizado.
- Me agrada ver que el código está realizado a tu manera, se ve que haz aprendido mucho en este proyecto.

### Tests:
Bien enfocado en que tu código esté orientado a test, buen nivel de coverage.

Muy bien, sigue así! recuerda siempre planificar bien tu tiempo en cada proyecto.

**Comment by Geraldine13** [comment]
Estimada Ruth:

Gracias por tu feedback, que me motiva a seguir mejorando.

Saludos,
